language: bash
services: docker

env:
  - IMAGE=0.10.3
  - IMAGE=0.11.1
  - IMAGE=0.11.2
  - IMAGE=classic/0.11.2.cl1
  - IMAGE=xt/0.11B
  - IMAGE=xt/0.11C
  - IMAGE=xt/0.11D

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$IMAGE"

script:
  - docker build -t bitcoin .
  - ~/official-images/test/run.sh bitcoin

after_script:
  - docker images
