name: Build Docker Image

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: actorforth/bitcoin-cash-node

jobs:
  build-bchn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          export TAG_BITCOINCASHNODE=v24.0.0
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG_BITCOINCASHNODE -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ./node/24.0.0

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v24.0.0
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  build-bu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          export TAG_BITCOINUNLIMITED=v1.10.0.0
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG_BITCOINUNLIMITED -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ./unlimited/1.10.0.0

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1.10.0.0
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
